#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

INPUT_FILE="$REPO_ROOT/images/jovial.png"
REPORT_BASE_DIR="${1:-$SCRIPT_DIR/ratio_reports}"
TIMESTAMP="$(date '+%Y%m%d_%H%M%S')"
REPORT_DIR="$REPORT_BASE_DIR/jovial_tuning_$TIMESTAMP"
BEST_PARAMS_FILE="$SCRIPT_DIR/jovial_best_params.env"

# Defaults tuned for jovial.png so harness explores practical high-throughput grids first.
HARNESS_DIMENSIONS="${DIMENSIONS:-96x54 128x72 80x45 64x36 48x27}"
HARNESS_CELLS="${CELLS:-10 8 6 12}"
HARNESS_BITS="${BITS:-2 4 1}"
HARNESS_FPS="${FPS_VALUES:-30 24 60}"
HARNESS_REPEATS="${REPEATS:-3 2 1}"
HARNESS_TAIL="${TAIL_FRAMES:-0}"
HARNESS_MAX_TRIALS="${MAX_TRIALS_PER_INPUT:-36}"

if [[ ! -f "$INPUT_FILE" ]]; then
  echo "Input image not found: $INPUT_FILE" >&2
  exit 1
fi

mkdir -p "$REPORT_BASE_DIR"

echo "Running ratio harness for: $INPUT_FILE"
echo "Report directory: $REPORT_DIR"

echo "Search config:"
echo "  DIMENSIONS=$HARNESS_DIMENSIONS"
echo "  CELLS=$HARNESS_CELLS"
echo "  BITS=$HARNESS_BITS"
echo "  FPS_VALUES=$HARNESS_FPS"
echo "  REPEATS=$HARNESS_REPEATS"
echo "  TAIL_FRAMES=$HARNESS_TAIL"
echo "  MAX_TRIALS_PER_INPUT=$HARNESS_MAX_TRIALS"

DIMENSIONS="$HARNESS_DIMENSIONS" \
CELLS="$HARNESS_CELLS" \
BITS="$HARNESS_BITS" \
FPS_VALUES="$HARNESS_FPS" \
REPEATS="$HARNESS_REPEATS" \
TAIL_FRAMES="$HARNESS_TAIL" \
MAX_TRIALS_PER_INPUT="$HARNESS_MAX_TRIALS" \
"$REPO_ROOT/ratio_harness.sh" "$INPUT_FILE" "$REPORT_DIR"

SUMMARY_CSV="$REPORT_DIR/summary.csv"
if [[ ! -f "$SUMMARY_CSV" ]]; then
  echo "No summary found: $SUMMARY_CSV" >&2
  exit 1
fi

best_line="$(awk -F, 'NR>1 && $1=="jovial.png" && $3=="ok" { print; exit }' "$SUMMARY_CSV")"
if [[ -z "$best_line" ]]; then
  echo "No successful tuning result found in $SUMMARY_CSV" >&2
  exit 1
fi

winning_params="$(awk -F, 'NR>1 && $1=="jovial.png" && $3=="ok" { print $10; exit }' "$SUMMARY_CSV")"
if [[ -z "$winning_params" ]]; then
  echo "Could not parse winning parameters from summary." >&2
  exit 1
fi

cols="$(sed -n 's/.*cols=\([0-9]\+\).*/\1/p' <<< "$winning_params")"
rows="$(sed -n 's/.*rows=\([0-9]\+\).*/\1/p' <<< "$winning_params")"
cell="$(sed -n 's/.*cell=\([0-9]\+\).*/\1/p' <<< "$winning_params")"
bits="$(sed -n 's/.*bits=\([0-9]\+\).*/\1/p' <<< "$winning_params")"
fps="$(sed -n 's/.*fps=\([0-9]\+\).*/\1/p' <<< "$winning_params")"
repeat="$(sed -n 's/.*repeat=\([0-9]\+\).*/\1/p' <<< "$winning_params")"
tail="$(sed -n 's/.*tail=\([0-9]\+\).*/\1/p' <<< "$winning_params")"

if [[ -z "$cols" || -z "$rows" || -z "$cell" || -z "$bits" || -z "$fps" || -z "$repeat" || -z "$tail" ]]; then
  echo "Failed to extract complete parameter set from: $winning_params" >&2
  exit 1
fi

cat > "$BEST_PARAMS_FILE" <<EOF
# Auto-generated by examples/tune_jovial_for_smallest_mp4.sh
# Source report: $REPORT_DIR
COLS=$cols
ROWS=$rows
CELL=$cell
BITS_PER_CELL=$bits
FPS=$fps
REPEAT=$repeat
TAIL_FRAMES=$tail
EOF

echo "Wrote tuned parameters: $BEST_PARAMS_FILE"
echo "Winning parameters: $winning_params"
echo "Next steps:"
echo "  1) ./examples/run_encode_jovial.sh"
echo "  2) ./examples/run_decode_jovial.sh"
